name: Laravel Pint

on:
  push:
    paths:
      - '**.php'

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run pint
        run: ./vendor/bin/pint --test